@startuml "Диаграмма контекста текущего состояние системы"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml


Boundary(devices, "устройства") {
    Person(Датчик, Датчик, "Датчик температуры", robot)
    Person(Реле, Реле, "Реле регялции вкл/выкл отопление", robot2)
}

Boundary(onsite_system, "Внешние сервисы") {

    System_Ext(WebUI, WebUI, "Некая система на стороне клиента котороая предоставляет интерфейс")
    System_Ext(Шлюз, Шлюз, "Некая система на стороне клиента котороая взаимодействует с устройствами и шлет статусы в систему")
}

Boundary(humans, "пользователи") {
    Person(Пользователь, Пользователь, "Обычный пользователь, житель дома")
    Person(Внедренец, Внедренец, "Специалист настраивающий систему")
}

Boundary(warmHouseBoundary, "Теплый дом") {
    System(ТеплыйДомСистема, ТеплыйДомСистема, "Система теплый дом")
    SystemDb(ТеплыйДомБД, ТеплыйДомБД)
}


Rel(Пользователь, WebUI, "Удаленно просматривает температуру")
Rel(Пользователь, WebUI, "Удаленно управляет реле")
Rel(WebUI, Шлюз, "Пересылает данные")
Rel(Реле, Шлюз, "вкл/выкл реле")
Rel(Датчик, Шлюз, "предоставляет температуру")
Rel(Внедренец, Шлюз, "Подключает дома")

Rel(Внедренец, ТеплыйДомСистема, "Подключает дома")
Rel(Шлюз, ТеплыйДомСистема, "Обновляет температуру")
Rel(Шлюз, ТеплыйДомСистема, "Обновляет статус реле")
Rel(Шлюз, ТеплыйДомСистема, "Запрашивает данные о текущем состоянии")
Rel(ТеплыйДомСистема, ТеплыйДомБД, "Сохраняет состояние")

@enduml